# Change these first
owner: wilyfreddie # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Movilizer Portal
    url: https://movilizer.com/Portal
  - name: Movilizer MDS
    url: https://movilizer.com/mds
  - name: Movilizer Demo Portal
    url: https://demo.movilizer.com/Portal
  - name: Movilizer Demo MDS
    url: https://demo.movilizer.com/mds
  - name: 1D+ Portal
    url: https://one-identity-plus.com/Portal
  - name: 1D+ Demo MDS
    url: https://one-identity-plus.com/mds

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: wilyfreddie.github.io/upptime
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: dark
  introTitle: "WilyFreddie's Website Monitor"
  introMessage: "Just a bunch of my sites that I want to monitor."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "0 /10 * * *"
